name: Cache - Delete

on: 
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository Name'
        default: 'danilocolombi/teste'
        required: true
      cache-id:
        description: 'Cache Key'
        default: 1
        required: true
        type: number

jobs:
  delete:
    runs-on: ubuntu-latest

    env:
      REPO: ${{ github.event.inputs.repository }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: List Cache Before Deleting
        run: gh cache list -R $REPO
    
      - name: Delete Cache
        run: gh cache delete $CACHE_ID -R $REPO
        env:
          CACHE_ID: ${{ github.event.inputs.cache-id }}

      - name: List Cache After Deleting
        run: gh cache list -R $REPO