name: Cache - List

on: 
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository Name'
        default: 'danilocolombi/teste'
        required: true

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: List Cache
        run: 'gh cache list --repo ${{ github.event.inputs.repository}}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}