name: 'Change Repo Visibility'
on: 
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Name of the Repo'
        default: ''
        required: true
      repo-visibility:
        description: 'Visibility of the Repo'
        default: 'private'
        required: true
  
jobs:
  change-visibility:
    runs-on: ubuntu-latest
    steps:
      - name: List Repos
        run: 'gh repo list'
        env:
          GH_TOKEN: ${{ GH_TOKEN }}
      
      - name:
        
