name: 'Change Repo Visibility'
on: 
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Name of the Repo'
        default: ''
        required: true
      repo-visibility:
        description: 'Visibility of the Repo'
        default: 'private'
        required: true
  
jobs:
  change-visibility:
    runs-on: ubuntu-latest
    steps:
      - name: List Repos
        run: 'gh repo list'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
      - name: Set Repo Public
        run:  |
          gh repo edit ${{ vars.GITHUB_REPOSITORY_OWNER}}/${{ github.event.inputs.repo-name }} \
          --visibility=${{ github.event.inputs.repo-visibility }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
