name: 'Create Project'

on: 
  workflow_dispatch:
    inputs:
      project-name:
        description: 'Name of the Project'
        default: ''
        required: true
        
jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub CLI
        run: |
         type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
          
      - name: List Projects
        run: gh project list
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}
