name: 'Create Project'

on: 
  workflow_dispatch:
    inputs:
      project-name:
        description: 'Name of the Project'
        default: ''
        required: true
        
jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - name: Update GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y
          
      - name: List Projects
        run: gh project list
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
