
  name: 'Create Gist'
  
  on:
    workflow_dispatch:
      inputs:
        gist-name:
          description: 'Name of the gist'
          required: true
          default: ''
  jobs:
    create-gist:
      runs-on: ubuntu-latest
      
      steps:
      
      - name: Checkout Repository
        uses: 'actions/checkout@v2'
        
      - name: List Gists
        run: 'gh gist list'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Create Gist
        run: 'gh gist create --public .github/workflows/delete-repo.yml'
