name: Issue - Reopen

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'Issue Number'
        default: 1
        required: true
        type: number
      repo-name:
        description: 'Repo Name'
        default: 'danilocolombi/teste'
        required: true

jobs:
  reopen:
    runs-on: ubuntu-latest

    steps:
      - name: List Issues Before Reopening
        run: gh issue list --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Reopen Issue
        run: gh issue reopen ${{ github.event.inputs.issue-number }} --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: List Issues After Reopening
        run: gh issue list --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}