name: Issue - Comment

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'Issue Number'
        default: 1
        required: true
        type: number
      comment:
        description: 'Comment'
        default: 'This issue is taking too long to be solved'
        required: true
      repo-name:
        description: 'Repository Name'
        default: 'danilocolombi/teste'
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: View Issue Before Comment
        run: gh issue view ${{ github.event.inputs.issue-number }}  --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Comment Issue
        run: |
          gh issue comment ${{ github.event.inputs.issue-number }} 
          --body "${{ github.event.inputs.comment}}" 
          --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: View Issue After Comment
        run: gh issue view ${{ github.event.inputs.issue-number }}  --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}