name: Issue - List

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repo Name'
        default: 'danilocolombi/teste'
        required: true

jobs:
  list:
    runs-on: ubuntu-latest

    steps:
      - name: List Issues
        run: gh issue list --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN ${{ secrets.GH_TOKEN }} 