name: Project - List

on: 
  workflow_dispatch:
    inputs:
      owner:
        description: 'Project Owner'
        required: true
        default: 'danilocolombi'

jobs:
  list:
    runs-on: ubuntu-latest
    
    steps:   
      - name: List Projects
        run: gh project list --owner ${{ github.event.inputs.owner }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}
