name: Project - Item Delete

on:
  workflow_dispatch:
    inputs:
      project-number:
        description: 'Project Number'
        required: true
        default: 1
        type: number
      item-id:
        description: 'Item Id'
        required: true
        default: ''
        type: string

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: List Items Before Deleting
        run: gh project item-list ${{ github.event.inputs.project-number }} --owner "@me" --limit 100
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}

      - name: Delete Item
        run: gh project item-delete ${{ github.event.inputs.project-number }} --owner "@me" --id ${{ github.event.inputs.item-id }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}
          
      - name: List Items After Deleting
        run: gh project item-list ${{ github.event.inputs.project-number }} --owner "@me" --limit 100
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}