name: Project - View

on: 
  workflow_dispatch:
    inputs:
      project-number:
        description: 'Project Number'
        default: 1
        required: true
        type: number
jobs:
  view:
    runs-on: ubuntu-latest
    steps:
      - name: View Project
        run: gh project view ${{ github.event.inputs.project-number }} --owner @me
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}