name: Project - Create

on: 
  workflow_dispatch: 
    inputs:
      title:
        description: 'Project Title'
        required: true
        default: 'My Project'

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: List Projects Before Creating
        run: gh project list --owner @me
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}
    
      - name: Create Project
        run: gh project create --owner @me --title "${{ github.event.inputs.title }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}

      - name: List Projects After Creating
        run: gh project list --owner @me
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}