name: Project - Field List

on:
  workflow_dispatch:
    inputs:
      project-number:
        description: 'Project Number'
        required: true
        default: 1
        type: number

jobs:
  list:
    runs-on: ubuntu-latest

    steps:
      - name: List Fields
        run: gh project field-list ${{ github.event.inputs.project-number }} --owner "@me"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}