name: Project - Item List

on:
  workflow_dispatch:
    inputs:
      project-number:
        description: 'Project Number'
        required: true
        default: 1
        type: number

jobs:
  list:
    runs-on: ubuntu-latest

    steps:
      - name: List Items
        run: gh project item-list ${{ github.event.inputs.project-number}} --owner "@me" --limit 100
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_CLASSIC }}
            