name: Release - List

on: 
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repo Name'
        default: 'danilocolombi/teste'
        required: true
      tag-name:
        description: 'Tag Name'
        default: 'v1.0.0'
        required: true
jobs:
  list:
    runs-on: ubuntu-latest

    steps:
      - name: List Releases
        run: gh release list --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}