name: Repo - Change Visibility
on: 
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Name of the Repo'
        default: ''
        required: true
      repo-visibility:
        description: 'Visibility of the Repo'
        default: 'private'
        required: true
  
jobs:
  change-visibility:
    runs-on: ubuntu-latest
    steps:
    
      - name: List Repos Before Change
        run: 'gh repo list'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
    
      - name: Set Repo Visibility
        run:  |
          gh repo edit ${{ github.repository_owner }}/${{ github.event.inputs.repo-name }} \
          --visibility=${{ github.event.inputs.repo-visibility }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: List Repos After Change
        run: 'gh repo list'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
