name: Repo - Enable Options
on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Name of the Repo'
        default: ''
        required: true
      enable-wiki:
        description: 'Enable Wiki'
        default: 'true'
        required: true
      enable-issues:
        description: 'Enable Issues'
        default: 'true'
        required: true
      enable-discussions:
        description: 'Enable Discussions'
        default: 'true'
        required: true
      enable-projects:
        description: 'Enable Projects'
        default: 'true'
        required: true
jobs:
  enable-repo-options:
    runs-on: ubuntu-latest
    steps:
    
      - name: List Repos
        run: gh repo list
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Enable Wiki
        run:  |
          gh repo edit ${{ github.repository_owner }}/${{ github.event.inputs.repo-name }} \
          --enable-wiki=${{ github.event.inputs.enable-wiki }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Enable Issues
        run: |
          gh repo edit ${{ github.repository_owner }}/${{ github.event.inputs.repo-name }} \
          --enable-issues=${{ github.event.inputs.enable-issues }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Enable Discussions
        run: |
          gh repo edit ${{ github.repository_owner }}/${{ github.event.inputs.repo-name }} \
          --enable-discussions=${{ github.event.inputs.enable-discussions }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Enable Projects
        run: |
          gh repo edit ${{ github.repository_owner }}/${{ github.event.inputs.repo-name }} \
          --enable-projects=${{ github.event.inputs.enable-projects }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
