name: Unarchive Repo

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Name of the Repo'
        default: ''
        required: true

jobs:
  unarchive:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: List Before Unarchive Repo
        run: 'gh repo list'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Unarchive Repo
        run: 'gh repo unarchive ${{ github.event.inputs.repo-name }} --yes'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: List After Unarchive Repos
        run: 'gh repo list'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
