name: Secret - Delete

on:
  workflow_dispatch:
    inputs:
      secret-name:
        description: 'Name of the Secret'
        default: 'MY_SECRET'
        required: true
      delete-repo-secret:
        description: 'Is it a Repo Secret?'
        default: true
        required: false
        type: boolean
      repo-name:
        description: 'Name of the Repo'
        default: 'danilocolombi/teste'
        required: false
      delete-user-secret:
        description: 'Is it a User Secret?'
        default: true
        required: false
        type: boolean
jobs:
  delete-secret:
    runs-on: ubuntu-latest
    steps:

      - name: Delete Repository Secret
        if: ${{ github.event.inputs.delete-repo-secret == 'true' }} 
        run: |
          gh secret delete ${{ github.event.inputs.secret-name }} \
          --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Delete Codespaces User Secret
        if: ${{ github.event.inputs.delete-user-secret == 'true' }}
        run: gh secret delete ${{ github.event.inputs.secret-name }} --user
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}