name: Set Secret

on:
  workflow_dispatch:
    inputs:
      secret-name:
        description: 'Name of the Secret'
        default: 'MY_SECRET'
        required: true
      secret-value:
        description: 'Value of the Secret'
        default: 'SUPER_SECRET'
        required: true
      set-repo-secret:
        description: 'Is it a Repo Secret?'
        default: true
        required: false
        type: boolean
      repo-name:
        description: 'Name of the Repo'
        default: 'danilocolombi/teste'
        required: false
      set-user-secret:
        description: 'Is it a User Secret?'
        default: true
        required: false
        type: boolean

env:
  SECRET_VALUE: 

jobs:
  set-secret:
    runs-on: ubuntu-latest
    steps:

      - name: Set Repository Secret
        if: ${{ github.event.inputs.set-repo-secret == true}}
        run: |
          gh secret set ${{ github.event.inputs.secret-name }} \
          --repo ${{ github.event.inputs.repo-name }} \
          --body ${{ github.event.inputs.secret-value }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set Codespaces User Secret
        if: ${{ github.event.inputs.set-user-secret == true }}
        run: |
          gh secret set {{ github.event.inputs.secret-name }} \
          --user \
          --body ${{ github.event.inputs.secret-value }}