name: Set Secret
on:
  workflow_dispatch:
    inputs:
      secret-name:
        description: 'Name of the Secret'
        default: ''
        required: true
      secret-value:
        description: 'Value of the Secret'
        default: ''
        required: true

env:
  SECRET_VALUE: ${{ github.event.inputs.secret-value }}

jobs:
  set-secret:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set Secret'
        run: gh secret set ${{ github.event.inputs.secret-name }} --env $SECRET_VALUE
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}