name: Secret - List

on:
  workflow_dispatch:
    inputs:
      list-user-secrets:
        description: 'List User Secrets?'
        required: true
        default: false
        type: boolean
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: List User Secrets
        if: ${{ github.event.inputs.list-user-secrets == 'true' }}
        run: gh secret list --user
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}