name: Secret - Set

on:
  workflow_dispatch:
    inputs:
      secret-name:
        description: 'Secret Name'
        default: 'MY_SECRET'
        required: true
      secret-value:
        description: 'Secret Value'
        default: 'SUPER_SECRET'
        required: true
      repo-name:
        description: 'Repo Name'
        default: 'danilocolombi/teste'
        required: false

jobs:
  set-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Set Repository Secret
        run: |
          gh secret set ${{ github.event.inputs.secret-name }} \
          --repo ${{ github.event.inputs.repo-name }} \
          --body ${{ github.event.inputs.secret-value }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}