name: Workflow - List

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repo Name'
        default: 'danilocolombi/github-automation'
        required: true
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: List Workflows
        run: gh workflow list --repo ${{ github.event.inputs.repo-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}